spring:
  devtools:
    livereload:
      #?? ???? ??? ?? ? ?? ????
      enabled: true
  thymeleaf:
    #templates ????? ??? ??? ??? ??, ??? ?? ??
    check-template-location: false
    #thymeleaf ?? ??
    prefix: classpath:/templates/
    #thymeleaf? ?? ??? ??? ??? (????? true)
    cache: false
  jpa:
    open-in-view: false
  profiles:
    active: local
